"""Add contact table

Revision ID: 583a441f53f
Revises: None
Create Date: 2014-11-03 09:59:49.601829

"""

# revision identifiers, used by Alembic.
revision = '583a441f53f'
down_revision = None

from datetime import datetime
from alembic import op
from sqlalchemy import text
import sqlalchemy as sa


def upgrade():
    op.create_table('contact',
        sa.Column('id', sa.Integer(), sa.Sequence('core_seq_general'), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False, default=datetime.now()),
        sa.Column('version', sa.DateTime(), nullable=False, default=datetime.now(), onupdate=datetime.now),
        sa.Column('enabled', sa.Boolean(), nullable=False, default=True),
        sa.Column('firstname', sa.String(), nullable=False),
        sa.Column('lastname', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('login', sa.Column('contact_id', sa.Integer(), sa.ForeignKey('contact.id'), nullable=True))
    connection = op.get_bind()
    t = text('SELECT id, username FROM login')
    for login_id, username in connection.execute(t):
        t = text('''
            INSERT INTO contact(id, created, version, enabled, firstname, lastname, email)
            VALUES (:id, :created, :version, :enabled, :firstname, :lastname, :email)
            RETURNING id
        ''').bindparams(
            id=connection.execute(sa.Sequence('core_seq_general')),
            created=datetime.now(),
            version=datetime.now(),
            enabled=True,
            firstname='',
            lastname='',
            email=username
        )
        contact_id = connection.execute(t).fetchone()[0]
        t = text('''
            UPDATE login
            SET contact_id = :contact_id
            WHERE id = :id
        ''').bindparams(
            id=login_id,
            contact_id=contact_id
        )
        connection.execute(t)
    op.alter_column('login', 'contact_id', nullable=False)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login', 'contact_id')
    op.drop_table('contact')
    ### end Alembic commands ###
